### PR TITLE
Add instructions box

### PR DESCRIPTION
**Pull request by laptou**
The instructions box at the bottom of the screen now contains a prompt indicating what the player should do.

image

### CODE REVIEW

**Comment by laptou** [comment]
@isabellawu90 why did you assign yourself and Kyra to this PR?

**Comment by isabellawu90** [comment]
> @isabellawu90 why did you assign yourself and Kyra to this PR?

because kyra and i were gonna work on this together? we decided to do diff things now but originally that was the plan

**Comment by laptou** [comment]
iirc Izzy and I agreed that Izzy would continue to work on the instructions box in a separate PR, so can we get this one reviewed?

**Review by isabellawu90 — APPROVED** [review]

**Comment by laptou** [comment]
@kyralee22 @owenxr please review

**Review by owenxr — APPROVED** [review]

**Review by owenxr — APPROVED** [review]

**Review by kyralee22 — APPROVED** [review]

**Pull request merged**
