### PR TITLE
Fix crash when the player tries to input a disconnected word

### LINKED ISSUE #46: Game should not crash when the player inputs a disconnected word

### PR DESCRIPTION
**Pull request by laptou**
- Resolves #46

### CODE REVIEW

**Review by kyralee22 — CHANGES_REQUESTED** [review]
The points aren't incrementing for each player anymore. Otherwise, looks good.

**Comment by laptou** [comment]
> The points aren't incrementing for each player anymore. 

Fixed this

**Review by kyralee22 — CHANGES_REQUESTED** [review]
Screen Shot 2021-11-13 at 12 46 53 PM
The player points is now incrementing points for the wrong player

**Comment by laptou** [comment]
> The player points is now incrementing points for the wrong player

Oops. Fixed this too

**Comment by laptou** [comment]
bump @kyralee22 @isabellawu90 @owenxr

**Review by owenxr — APPROVED** [review]

**Review by kyralee22 — APPROVED** [review]

**Pull request merged**
