### PR TITLE
Tile multipliers

### PR DESCRIPTION
**Pull request by laptou**
Screen Shot 2021-11-11 at 8 13 02 AM
changed pattern for tile multipliers and all multiplier types are on the board now

### CODE REVIEW

**Review by kyralee22 — COMMENTED** [review]
Should these "DL"/"DW"/ etc. strings for each multiplier be visible on the tiles? I can't currently see them on the board.

**Review by kyralee22 — APPROVED** [review]

**Comment by isabellawu90** [comment]
Screen Shot 2021-11-10 at 12 43 39 PM
tile multipliers for Triple Word and Double Word now appear infinitely on board in repeating X's

**Review by kyralee22 — CHANGES_REQUESTED** [review]
Can we make it so that when a user inputs a letter over a tile, the "DW"/"TW" is removed and replaced with the letter?

Also, should we color coordinate each tile (like what we discussed in the meeting)? It might be more intuitive that way, so the letter doesn't randomly just change color when put on a certain tile. 

Otherwise, looks good :)

**Comment by laptou** [comment]
> Also, should we color coordinate each tile (like what we discussed in the meeting)? It might be more intuitive that way, so the letter doesn't randomly just change color when put on a certain tile.

I agree with this, but I think this should be in a separate PR.

**Review by owenxr — APPROVED** [review]

**Comment by laptou** [comment]
bump @kyralee22

**Comment by kyralee22** [comment]
> bump @kyralee22

My prior  request about replacing "DW" with the actual letter placed there wasn't addressed. Is this being implemented in the tile highlight PR?

**Comment by isabellawu90** [comment]
> > bump @kyralee22
> 
> My prior request about replacing "DW" with the actual letter placed there wasn't addressed. Is this being implemented in the tile highlight PR?

I thought no but I can do it for this PR

**Comment by laptou** [comment]
> > bump @kyralee22
> 
> My prior request about replacing "DW" with the actual letter placed there wasn't addressed. Is this being implemented in the tile highlight PR?

This has been fixed. Is there anything else blocking this PR?

**Review by kyralee22 — APPROVED** [review]

**Pull request merged**
